### ISSUE TITLE
Support Vue 2

### ISSUE THREAD

**Issue by larionov** [brattonross/vite-plugin-voie#8]
Hello!

I would like to add an option to support vue 2 (with https://github.com/underfin/vite-plugin-vue2), do you think it's a good idea?
How to better implement it? Should it allow user to provide any import string (sync/async) or better limit it to the vue 3/vue 2 support?

**Comment by brattonross** [comment]
Hey, thanks for your interest in the project!

Since Vite is aimed at Vue 3, supporting Vue 2 isn't a priority in my eyes. I would prefer to expend my effort creating a _great_ library for Vue 3 rather than a _good_ library for Vue 2 and 3. I hope you can understand my reasoning 😃

If you really want a Vue 2 compatible solution, I expect that you can wrap [vue-route-generator](https://github.com/ktsn/vue-route-generator) in a Vite plugin.

**Comment by cdll** [comment]
same issue here with https://github.com/underfin/vite-plugin-vue2
